#!/bin/bash

# Read pywal colors
COLORS_FILE="$HOME/.cache/wal/colors"

if [ ! -f "$COLORS_FILE" ]; then
    exit 1
fi

BG=$(sed -n '1p' "$COLORS_FILE")
RED=$(sed -n '2p' "$COLORS_FILE")
GREEN=$(sed -n '3p' "$COLORS_FILE")
YELLOW=$(sed -n '4p' "$COLORS_FILE")
BLUE=$(sed -n '5p' "$COLORS_FILE")
PURPLE=$(sed -n '6p' "$COLORS_FILE")
CYAN=$(sed -n '7p' "$COLORS_FILE")
FG=$(sed -n '8p' "$COLORS_FILE")
MUTED=$(sed -n '9p' "$COLORS_FILE")

# Generate tmux color config
cat > "$HOME/.config/tmux/pywal-colors.conf" <<EOF
# Auto-generated by pywal-theme.sh — do not edit manually

# Status bar
set -g status-style "bg=${BG},fg=${FG}"

# Left: session name
set -g status-left "#[bg=${BLUE},fg=${BG},bold]  #S #[bg=${BG},fg=${BLUE}] "

# Right: path, date, time
set -g status-right "#[fg=${MUTED}]│ #[fg=${PURPLE}]#{=40:pane_current_path} #[fg=${MUTED}]│ #[fg=${YELLOW}]%a %b %d #[fg=${MUTED}]│ #[fg=${CYAN},bold]%H:%M "

# Inactive window
set -g window-status-format "#[fg=${MUTED}] #I:#W "

# Active window
set -g window-status-current-format "#[fg=${BG},bg=${CYAN},bold] #I:#W #[bg=${BG}] "

# Pane borders
set -g pane-border-style "fg=${MUTED}"
set -g pane-active-border-style "fg=${BLUE}"

# Messages
set -g message-style "bg=${YELLOW},fg=${BG},bold"
set -g message-command-style "bg=${MUTED},fg=${FG}"

# Copy mode
set -g mode-style "bg=${BLUE},fg=${BG}"

# Clock
set -g clock-mode-colour "${CYAN}"
EOF
