theme = "catppuccin_mocha"

[editor]
auto-format = true

[keys.normal]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]
C-s = ":w"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
